### ISSUE TITLE
gradlew.bat

### ISSUE THREAD

**Issue by r1zkyPrasetyo** [nizwar/cek_akreditasi#1]
https://prnt.sc/psrgm5

Initializing gradle...
Resolving dependencies...
* Error running Gradle:
ProcessException: Process "D:\Rizky\dev\android\flutter\cek_akreditasi\android\gradlew.bat" exited abnormally:

  Command: D:\Rizky\dev\android\flutter\cek_akreditasi\android\gradlew.bat app:properties

Finished with error: Please review your Gradle project setup in the android/ folder.

ini kenapa ya gan ?

**Comment by nizwar** [comment]
Coba pull lagi gan, udah bisa apa belum?

**Comment by r1zkyPrasetyo** [comment]
itu kenapa gan ?

**Comment by nizwar** [comment]
Mungkin karna gradlenya yg disetup udah siap rilis gan, udah setting key.properties dsb, tapi keynya ga saya masukin ke repo ini
